// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOOECynl9VrgVu-kUIsNS2-VWU9x8Q_Vc',
    appId: '1:760779874111:web:919e724580ac40fa8b3d8a',
    messagingSenderId: '760779874111',
    projectId: 'registro-clases-dev',
    authDomain: 'registro-clases-dev.firebaseapp.com',
    storageBucket: 'registro-clases-dev.firebasestorage.app',
    measurementId: 'G-KZWQL0G71E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO6Zx0a8JktexvUR91lcu6sf4z0zcs0uk',
    appId: '1:760779874111:android:497709fd7508b73a8b3d8a',
    messagingSenderId: '760779874111',
    projectId: 'registro-clases-dev',
    storageBucket: 'registro-clases-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTQWGHfUP7TpHoLxwDXC17xvI1urGuRfU',
    appId: '1:760779874111:ios:5b1ee2f25c6eb3b38b3d8a',
    messagingSenderId: '760779874111',
    projectId: 'registro-clases-dev',
    storageBucket: 'registro-clases-dev.firebasestorage.app',
    iosBundleId: 'com.example.registroClases',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTQWGHfUP7TpHoLxwDXC17xvI1urGuRfU',
    appId: '1:760779874111:ios:5b1ee2f25c6eb3b38b3d8a',
    messagingSenderId: '760779874111',
    projectId: 'registro-clases-dev',
    storageBucket: 'registro-clases-dev.firebasestorage.app',
    iosBundleId: 'com.example.registroClases',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOOECynl9VrgVu-kUIsNS2-VWU9x8Q_Vc',
    appId: '1:760779874111:web:f0c4b07cbccb17168b3d8a',
    messagingSenderId: '760779874111',
    projectId: 'registro-clases-dev',
    authDomain: 'registro-clases-dev.firebaseapp.com',
    storageBucket: 'registro-clases-dev.firebasestorage.app',
    measurementId: 'G-FFHSC8DPLT',
  );
}
